/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.BicicletaData;
import Data.Conexion;
import Data.ReparacionData;
import Data.RepuestoData;
import Data.ServicioData;
import Modelo.Reparacion;
import Modelo.Repuesto;
import Modelo.Servicio;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class MainForm extends javax.swing.JFrame {

    Connection con = Conexion.getConexion();
    BicicletaData bData = new BicicletaData();
    ReparacionData repData = new ReparacionData();
    RepuestoData repuestoData = new RepuestoData();
    ServicioData sData = new ServicioData();
    private DefaultTableModel tabla;

    public MainForm() {
        initComponents();
        tabla = new DefaultTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reparacionBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabInicio = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jRBNoEntregadas = new javax.swing.JRadioButton();
        jRBNoTerminadas = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTDni = new javax.swing.JTextField();
        btnBuscarXdni = new javax.swing.JPanel();
        jLBuscarDni = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jTNumSerie = new javax.swing.JTextField();
        jTRepuesto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTPrecio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLAgregarRep = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTFRepNSerie = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLRepuestoBorrar = new javax.swing.JLabel();
        jTFBuscarRepuesto = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTFBuscarPrecio = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLActualizarRepuesto = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLBuscarRepuesto = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTFservicio = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTFServicioPrecio = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLAgregarServicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTFCodServ = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jLActServ = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLBorrarServ = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLBuscarServicio = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jTFPrecioB = new javax.swing.JTextField();
        jTFServicioB = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField15 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField16 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jComboBox8 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jTextField22 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField23 = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jSpinner3 = new javax.swing.JSpinner();
        jPanel27 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        repuestoBtn = new javax.swing.JLabel();
        clientBtn = new javax.swing.JLabel();
        servicioBtn = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Taller de Bicicletas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        reparacionBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reparacionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reparacion.png"))); // NOI18N
        jPanel1.add(reparacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 360, 40, 40));

        jLabel3.setBackground(new java.awt.Color(35, 35, 35));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banner.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1000, 40));

        jTabInicio.setBackground(new java.awt.Color(35, 35, 35));
        jTabInicio.setForeground(new java.awt.Color(35, 35, 35));

        jPanel2.setBackground(new java.awt.Color(35, 35, 35));
        jPanel2.setForeground(new java.awt.Color(35, 35, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(103, 103, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID de reparación", "ID de servicio", "ID ", "Fecha de entrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 660, 250));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Historial de Reparaciones");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 290, 30));

        jRBNoEntregadas.setBackground(new java.awt.Color(51, 51, 51));
        jRBNoEntregadas.setForeground(new java.awt.Color(255, 255, 255));
        jRBNoEntregadas.setText("Reparaciones No Entregadas");
        jRBNoEntregadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoEntregadasActionPerformed(evt);
            }
        });
        jPanel3.add(jRBNoEntregadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jRBNoTerminadas.setBackground(new java.awt.Color(51, 51, 51));
        jRBNoTerminadas.setForeground(new java.awt.Color(255, 255, 255));
        jRBNoTerminadas.setText("Reparaciones No Terminadas");
        jRBNoTerminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNoTerminadasActionPerformed(evt);
            }
        });
        jPanel3.add(jRBNoTerminadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 20));

        jTDni.setBackground(new java.awt.Color(51, 51, 51));
        jTDni.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTDni.setForeground(new java.awt.Color(123, 123, 123));
        jTDni.setText("Ingrese el DNI del dueño");
        jTDni.setBorder(null);
        jTDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDniActionPerformed(evt);
            }
        });
        jPanel3.add(jTDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, 20));

        btnBuscarXdni.setBackground(new java.awt.Color(0, 134, 190));
        btnBuscarXdni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarXdniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarXdniMouseExited(evt);
            }
        });
        btnBuscarXdni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBuscarDni.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLBuscarDni.setForeground(new java.awt.Color(255, 255, 255));
        jLBuscarDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBuscarDni.setText("Buscar");
        jLBuscarDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBuscarDniMouseClicked(evt);
            }
        });
        btnBuscarXdni.add(jLBuscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 80, 20));

        jPanel3.add(btnBuscarXdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 80, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 790, 410));

        jTabInicio.addTab("tab1", jPanel2);

        jPanel5.setBackground(new java.awt.Color(35, 35, 35));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Repuestos");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 230, 20));

        jTNumSerie.setBackground(new java.awt.Color(51, 51, 51));
        jTNumSerie.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTNumSerie.setForeground(new java.awt.Color(123, 123, 123));
        jTNumSerie.setText("Ingrese N° de Serie");
        jTNumSerie.setBorder(null);
        jTNumSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumSerieActionPerformed(evt);
            }
        });
        jPanel6.add(jTNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 230, 20));

        jTRepuesto.setBackground(new java.awt.Color(51, 51, 51));
        jTRepuesto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTRepuesto.setForeground(new java.awt.Color(123, 123, 123));
        jTRepuesto.setText("Ingrese Repuesto");
        jTRepuesto.setBorder(null);
        jTRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRepuestoActionPerformed(evt);
            }
        });
        jPanel6.add(jTRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 230, 20));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 120, 230, 20));

        jTPrecio.setBackground(new java.awt.Color(51, 51, 51));
        jTPrecio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTPrecio.setForeground(new java.awt.Color(123, 123, 123));
        jTPrecio.setText("Ingrese el Precio");
        jTPrecio.setBorder(null);
        jTPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecioActionPerformed(evt);
            }
        });
        jPanel6.add(jTPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 230, 20));

        jSeparator5.setForeground(new java.awt.Color(60, 63, 65));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 350, 20));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Agregar");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel7.setBackground(new java.awt.Color(0, 134, 190));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAgregarRep.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLAgregarRep.setForeground(new java.awt.Color(255, 255, 255));
        jLAgregarRep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAgregarRep.setText("Agregar");
        jLAgregarRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAgregarRepMouseClicked(evt);
            }
        });
        jPanel7.add(jLAgregarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 170, 230, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 350, 200));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 350, 450));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Buscar");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jTFRepNSerie.setBackground(new java.awt.Color(51, 51, 51));
        jTFRepNSerie.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFRepNSerie.setForeground(new java.awt.Color(123, 123, 123));
        jTFRepNSerie.setText("Ingrese N° de Serie");
        jTFRepNSerie.setBorder(null);
        jTFRepNSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRepNSerieActionPerformed(evt);
            }
        });
        jPanel8.add(jTFRepNSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 230, 20));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 230, 20));

        jPanel9.setBackground(new java.awt.Color(0, 134, 190));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLRepuestoBorrar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLRepuestoBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jLRepuestoBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRepuestoBorrar.setText("Borrar");
        jLRepuestoBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLRepuestoBorrarMouseClicked(evt);
            }
        });
        jPanel9.add(jLRepuestoBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 90, 30));

        jTFBuscarRepuesto.setBackground(new java.awt.Color(51, 51, 51));
        jTFBuscarRepuesto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFBuscarRepuesto.setForeground(new java.awt.Color(123, 123, 123));
        jTFBuscarRepuesto.setText("Repuesto");
        jTFBuscarRepuesto.setBorder(null);
        jTFBuscarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFBuscarRepuestoActionPerformed(evt);
            }
        });
        jPanel8.add(jTFBuscarRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 130, 230, 20));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 230, 20));

        jTFBuscarPrecio.setBackground(new java.awt.Color(51, 51, 51));
        jTFBuscarPrecio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFBuscarPrecio.setForeground(new java.awt.Color(123, 123, 123));
        jTFBuscarPrecio.setText("Precio");
        jTFBuscarPrecio.setBorder(null);
        jTFBuscarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFBuscarPrecioActionPerformed(evt);
            }
        });
        jPanel8.add(jTFBuscarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 230, 20));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 200, 230, 20));

        jPanel10.setBackground(new java.awt.Color(0, 134, 190));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLActualizarRepuesto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLActualizarRepuesto.setForeground(new java.awt.Color(255, 255, 255));
        jLActualizarRepuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLActualizarRepuesto.setText("Actualizar");
        jLActualizarRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLActualizarRepuestoMouseClicked(evt);
            }
        });
        jPanel10.add(jLActualizarRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 90, 30));

        jPanel12.setBackground(new java.awt.Color(0, 134, 190));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBuscarRepuesto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLBuscarRepuesto.setForeground(new java.awt.Color(255, 255, 255));
        jLBuscarRepuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBuscarRepuesto.setText("Buscar");
        jLBuscarRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBuscarRepuestoMouseClicked(evt);
            }
        });
        jPanel12.add(jLBuscarRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 90, 30));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/la-carretera.png"))); // NOI18N
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 190));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 350, 450));

        jTabInicio.addTab("tab2", jPanel5);

        jPanel11.setBackground(new java.awt.Color(35, 35, 35));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Servicios");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Agregar");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jTFservicio.setBackground(new java.awt.Color(51, 51, 51));
        jTFservicio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFservicio.setForeground(new java.awt.Color(123, 123, 123));
        jTFservicio.setText("Ingrese Servicio");
        jTFservicio.setBorder(null);
        jTFservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFservicioActionPerformed(evt);
            }
        });
        jPanel13.add(jTFservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 230, 20));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 230, 20));

        jTFServicioPrecio.setBackground(new java.awt.Color(51, 51, 51));
        jTFServicioPrecio.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFServicioPrecio.setForeground(new java.awt.Color(123, 123, 123));
        jTFServicioPrecio.setText("Ingrese Precio");
        jTFServicioPrecio.setBorder(null);
        jTFServicioPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFServicioPrecioActionPerformed(evt);
            }
        });
        jPanel13.add(jTFServicioPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 110, 230, 20));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 130, 230, 20));

        jPanel14.setBackground(new java.awt.Color(0, 134, 190));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAgregarServicio.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLAgregarServicio.setForeground(new java.awt.Color(255, 255, 255));
        jLAgregarServicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAgregarServicio.setText("Agregar");
        jLAgregarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAgregarServicioMouseClicked(evt);
            }
        });
        jPanel14.add(jLAgregarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(125, 125, 125));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel13.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 20, 140));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel13.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 410, 150));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 860, 170));

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Buscar");
        jPanel15.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jTFCodServ.setBackground(new java.awt.Color(51, 51, 51));
        jTFCodServ.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFCodServ.setForeground(new java.awt.Color(123, 123, 123));
        jTFCodServ.setText("Ingrese Código de Servicio");
        jTFCodServ.setBorder(null);
        jTFCodServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodServActionPerformed(evt);
            }
        });
        jPanel15.add(jTFCodServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 20));

        jSeparator13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 230, 20));

        jPanel18.setBackground(new java.awt.Color(0, 134, 190));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLActServ.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLActServ.setForeground(new java.awt.Color(255, 255, 255));
        jLActServ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLActServ.setText("Actualizar");
        jLActServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLActServMouseClicked(evt);
            }
        });
        jPanel18.add(jLActServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jPanel15.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 100, 30));

        jPanel17.setBackground(new java.awt.Color(0, 134, 190));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBorrarServ.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLBorrarServ.setForeground(new java.awt.Color(255, 255, 255));
        jLBorrarServ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBorrarServ.setText("Borrar");
        jLBorrarServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBorrarServMouseClicked(evt);
            }
        });
        jPanel17.add(jLBorrarServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 100, 30));

        jPanel16.setBackground(new java.awt.Color(0, 134, 190));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBuscarServicio.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLBuscarServicio.setForeground(new java.awt.Color(255, 255, 255));
        jLBuscarServicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBuscarServicio.setText("Buscar");
        jLBuscarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBuscarServicioMouseClicked(evt);
            }
        });
        jPanel16.add(jLBuscarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 100, 30));

        jSeparator15.setForeground(new java.awt.Color(125, 125, 125));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel15.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 20, 140));

        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 170, 20));

        jTFPrecioB.setBackground(new java.awt.Color(51, 51, 51));
        jTFPrecioB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFPrecioB.setForeground(new java.awt.Color(123, 123, 123));
        jTFPrecioB.setText("Precio");
        jTFPrecioB.setBorder(null);
        jTFPrecioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPrecioBActionPerformed(evt);
            }
        });
        jPanel15.add(jTFPrecioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 170, 20));

        jTFServicioB.setBackground(new java.awt.Color(51, 51, 51));
        jTFServicioB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTFServicioB.setForeground(new java.awt.Color(123, 123, 123));
        jTFServicioB.setText("Servicio");
        jTFServicioB.setBorder(null);
        jTFServicioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFServicioBActionPerformed(evt);
            }
        });
        jPanel15.add(jTFServicioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 20));

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, 20));

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 860, 170));

        jTabInicio.addTab("tab3", jPanel11);

        jPanel19.setBackground(new java.awt.Color(35, 35, 35));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Reparaciones");
        jPanel19.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 30));

        jPanel20.setBackground(new java.awt.Color(51, 51, 51));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator14.setForeground(new java.awt.Color(0, 134, 190));
        jPanel20.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, 140, 20));

        jTextField11.setBackground(new java.awt.Color(51, 51, 51));
        jTextField11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("Elija Servicio");
        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 140, 20));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Reparación");
        jPanel20.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        jPanel25.setBackground(new java.awt.Color(0, 134, 190));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Actualizar");
        jPanel25.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPanel20.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 90, 30));

        jPanel24.setBackground(new java.awt.Color(0, 134, 190));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Borrar");
        jPanel24.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 30));

        jPanel21.setBackground(new java.awt.Color(0, 134, 190));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Agregar");
        jPanel21.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 90, 30));

        jTextField14.setBackground(new java.awt.Color(51, 51, 51));
        jTextField14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("Elija Bicileta");
        jTextField14.setBorder(null);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, 140, 20));

        jSeparator18.setForeground(new java.awt.Color(0, 134, 190));
        jPanel20.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 160, 140, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel20.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, 30));

        jTextField15.setBackground(new java.awt.Color(51, 51, 51));
        jTextField15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("Fecha de Entrada");
        jTextField15.setBorder(null);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 230, 140, 20));

        jSeparator19.setForeground(new java.awt.Color(0, 134, 190));
        jPanel20.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 250, 140, 20));

        jDateChooser1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel20.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 30));

        jTextField16.setBackground(new java.awt.Color(51, 51, 51));
        jTextField16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(123, 123, 123));
        jTextField16.setText("Ingrese Precio");
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel20.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 300, 140, 20));

        jSeparator20.setForeground(new java.awt.Color(0, 134, 190));
        jPanel20.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 320, 140, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel20.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 46, 160, 30));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 350, 450));

        jPanel22.setBackground(new java.awt.Color(51, 51, 51));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Repuestos");
        jPanel22.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        jTextField25.setBackground(new java.awt.Color(51, 51, 51));
        jTextField25.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(255, 255, 255));
        jTextField25.setText("Elija Reparación");
        jTextField25.setBorder(null);
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jPanel22.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        jSeparator29.setForeground(new java.awt.Color(0, 134, 190));
        jPanel22.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel22.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, 30));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel22.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, -1, 160));

        jPanel19.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 450, 250));

        jPanel26.setBackground(new java.awt.Color(51, 51, 51));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Agregar Repuestos a Reparaciones");
        jPanel26.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        jSeparator26.setForeground(new java.awt.Color(0, 134, 190));
        jPanel26.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 20));

        jTextField22.setBackground(new java.awt.Color(51, 51, 51));
        jTextField22.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(255, 255, 255));
        jTextField22.setText("Elija Repuesto");
        jTextField22.setBorder(null);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel26.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel26.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, 30));

        jTextField23.setBackground(new java.awt.Color(51, 51, 51));
        jTextField23.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jTextField23.setText("Cant.");
        jTextField23.setBorder(null);
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel26.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 40, 20));

        jSeparator27.setForeground(new java.awt.Color(0, 134, 190));
        jPanel26.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 20));
        jPanel26.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, -1));

        jPanel27.setBackground(new java.awt.Color(0, 134, 190));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Agregar");
        jPanel27.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 90, 30));

        jTextField24.setBackground(new java.awt.Color(51, 51, 51));
        jTextField24.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(255, 255, 255));
        jTextField24.setText("Elija Reparación");
        jTextField24.setBorder(null);
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel26.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 20));

        jSeparator28.setForeground(new java.awt.Color(0, 134, 190));
        jPanel26.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 20));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel26.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 160, 30));

        jPanel19.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 450, 190));

        jTabInicio.addTab("tab4", jPanel19);

        jPanel1.add(jTabInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 940, 510));

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("El Pepe");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 40));

        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/casa (1).png"))); // NOI18N
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 120, 40, 40));

        repuestoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        repuestoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/repuesto.png"))); // NOI18N
        jPanel1.add(repuestoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 40, 40));

        clientBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bicycle.png"))); // NOI18N
        jPanel1.add(clientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 240, 40, 40));

        servicioBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        servicioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/servicio.png"))); // NOI18N
        jPanel1.add(servicioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 300, 40, 40));

        jSeparator12.setForeground(new java.awt.Color(125, 125, 125));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 20, 320));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        jBSalir.setText("Salir");
        jBSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDniActionPerformed

    }//GEN-LAST:event_jTDniActionPerformed

    private void jTNumSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumSerieActionPerformed

    private void jTRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRepuestoActionPerformed

    private void jTPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPrecioActionPerformed

    private void jTFRepNSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRepNSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRepNSerieActionPerformed

    private void jTFBuscarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFBuscarRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFBuscarRepuestoActionPerformed

    private void jTFBuscarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFBuscarPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFBuscarPrecioActionPerformed

    private void jTFservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFservicioActionPerformed

    private void jTFServicioPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFServicioPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFServicioPrecioActionPerformed

    private void jTFCodServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodServActionPerformed

    private void jTFPrecioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPrecioBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPrecioBActionPerformed

    private void jTFServicioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFServicioBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFServicioBActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_homeBtnMouseEntered

    private void btnBuscarXdniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarXdniMouseEntered
        btnBuscarXdni.setBackground(new Color(0, 196, 223));
    }//GEN-LAST:event_btnBuscarXdniMouseEntered

    private void btnBuscarXdniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarXdniMouseExited
        btnBuscarXdni.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_btnBuscarXdniMouseExited

    private void jRBNoTerminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoTerminadasActionPerformed
        if (jRBNoTerminadas.isSelected()) {
            jRBNoEntregadas.setSelected(false);
        } else if (!jRBNoTerminadas.isSelected()) {
            borrarFilasTabla();
        }
    }//GEN-LAST:event_jRBNoTerminadasActionPerformed

    private void jLBuscarDniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBuscarDniMouseClicked
        String dniDuenio = jTDni.getText();
        bData.obtenerBiciCliente(dniDuenio);
    }//GEN-LAST:event_jLBuscarDniMouseClicked

    private void jRBNoEntregadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNoEntregadasActionPerformed
        if (jRBNoEntregadas.isSelected()) {
            jRBNoTerminadas.setSelected(false);
        } else if (!jRBNoEntregadas.isSelected()) {
            borrarFilasTabla();
        }
    }//GEN-LAST:event_jRBNoEntregadasActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jLAgregarRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAgregarRepMouseClicked
        Repuesto repuesto = new Repuesto();
        String numSerie = jTNumSerie.getText();
        String repuestoDec = jTRepuesto.getText();
        Float precio = Float.parseFloat(jTPrecio.getText());
        repuesto.setNum_serie(numSerie);
        repuesto.setDescripcion(repuestoDec);
        repuesto.setPrecio(precio);
        repuesto.setActivo(true);
        repuestoData.agregarRepuesto(repuesto);
        
        jTNumSerie.setText("");
        jTRepuesto.setText("");
        jTPrecio.setText("");
    }//GEN-LAST:event_jLAgregarRepMouseClicked

    private void jLBuscarRepuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBuscarRepuestoMouseClicked
        String numSerie = jTFRepNSerie.getText();
        System.out.println(repuestoData.obtenerRepuesto(numSerie));
    }//GEN-LAST:event_jLBuscarRepuestoMouseClicked

    private void jLActualizarRepuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLActualizarRepuestoMouseClicked
        Repuesto repuesto = new Repuesto();
        String numSerie = jTFRepNSerie.getText();
        String repuestoDec = jTFBuscarRepuesto.getText();
        Float precio = Float.parseFloat(jTFBuscarPrecio.getText());
        repuesto.setNum_serie(numSerie);
        repuesto.setDescripcion(repuestoDec);
        repuesto.setPrecio(precio);
        repuesto.setActivo(true);
        
        repuestoData.modificarRepuesto(repuesto, numSerie);
    }//GEN-LAST:event_jLActualizarRepuestoMouseClicked

    private void jLRepuestoBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLRepuestoBorrarMouseClicked
        String numSerie = jTFRepNSerie.getText();
        repuestoData.eliminarRepuestoPorNumSerie(numSerie);
    }//GEN-LAST:event_jLRepuestoBorrarMouseClicked

    private void jLAgregarServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAgregarServicioMouseClicked
        Servicio servicio = new Servicio();
        String serv = jTFservicio.getText();
        Float precio = Float.parseFloat(jTFServicioPrecio.getText());
        servicio.setDescripcion(serv);
        servicio.setPrecio(precio);
        servicio.setActivo(true);
        sData.agregarServicio(servicio);
        
        jTFservicio.setText("");
        jTFServicioPrecio.setText("");
    }//GEN-LAST:event_jLAgregarServicioMouseClicked

    private void jLBuscarServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBuscarServicioMouseClicked
        int serv = Integer.parseInt(jTFCodServ.getText());
        sData.obtenerServicio(serv);
        
    }//GEN-LAST:event_jLBuscarServicioMouseClicked

    private void jLBorrarServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBorrarServMouseClicked
        int serv = Integer.parseInt(jTFCodServ.getText());
        sData.eliminarServicioPorCodigo(serv);
    }//GEN-LAST:event_jLBorrarServMouseClicked

    private void jLActServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLActServMouseClicked
        Servicio servicio = new Servicio();
        int codSer = Integer.parseInt(jTFCodServ.getText());
        String serv = jTFServicioB.getText();
        Float precio = Float.parseFloat(jTFPrecioB.getText());
        servicio.setActivo(true);
        servicio.setDescripcion(serv);
        servicio.setPrecio(precio);
        sData.modificarServicio(servicio, codSer);
        jTFServicioB.setText("");
        jTFPrecioB.setText("");
        
    }//GEN-LAST:event_jLActServMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    private void borrarFilasTabla() {
        if (tabla != null) {
            int aux = tabla.getRowCount() - 1;
            for (int i = aux; i >= 0; i--) {
                tabla.removeRow(i);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscarXdni;
    private javax.swing.JLabel clientBtn;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLActServ;
    private javax.swing.JLabel jLActualizarRepuesto;
    private javax.swing.JLabel jLAgregarRep;
    private javax.swing.JLabel jLAgregarServicio;
    private javax.swing.JLabel jLBorrarServ;
    private javax.swing.JLabel jLBuscarDni;
    private javax.swing.JLabel jLBuscarRepuesto;
    private javax.swing.JLabel jLBuscarServicio;
    private javax.swing.JLabel jLRepuestoBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRBNoEntregadas;
    private javax.swing.JRadioButton jRBNoTerminadas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTextField jTDni;
    private javax.swing.JTextField jTFBuscarPrecio;
    private javax.swing.JTextField jTFBuscarRepuesto;
    private javax.swing.JTextField jTFCodServ;
    private javax.swing.JTextField jTFPrecioB;
    private javax.swing.JTextField jTFRepNSerie;
    private javax.swing.JTextField jTFServicioB;
    private javax.swing.JTextField jTFServicioPrecio;
    private javax.swing.JTextField jTFservicio;
    private javax.swing.JTextField jTNumSerie;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTextField jTRepuesto;
    private javax.swing.JTabbedPane jTabInicio;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JLabel reparacionBtn;
    private javax.swing.JLabel repuestoBtn;
    private javax.swing.JLabel servicioBtn;
    // End of variables declaration//GEN-END:variables
}
